spring.application.name=product-catalog

spring.data.mongodb.uri=mongodb://localhost:27017/product_catalog

server.port=9090

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

spring.web.cors.allowed-origin-patterns=http://localhost:5173
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*
