# Application name
spring.application.name=product-catalog

# PostgreSQL Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/product_catalog_db
spring.datasource.username=postgres
spring.datasource.password=Satya9987@

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server port (optional, defaults to 8080)
server.port=9090

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

# Allow frontend (Vite dev server) to call backend
spring.web.cors.allowed-origin-patterns=http://localhost:5173
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ecommerce



