#spring.application.name=product-catalog
#
#
#server.port=9090
#
#spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
#  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
#
#spring.web.cors.allowed-origin-patterns=http://localhost:5173
#spring.web.cors.allowed-methods=*
#spring.web.cors.allowed-headers=*



#
## \u2705 Correct exclusion paths for Spring Boot 4.x
#spring.autoconfigure.exclude=\
#  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
#  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
#  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
#
#spring.web.cors.allowed-origin-patterns=http://localhost:5173
#spring.web.cors.allowed-methods=*
#spring.web.cors.allowed-headers=*

#
#
## \u2705 Correct exclusion paths for Spring Boot 4.x
#spring.autoconfigure.exclude=\
#  org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
#  org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration,\
#  org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration,\
#  org.springframework.boot.devtools.autoconfigure.DevToolsDataSourceAutoConfiguration
#
#server.port=9090
#
#spring.web.cors.allowed-origin-patterns=http://localhost:5173
#spring.web.cors.allowed-methods=*
#spring.web.cors.allowed-headers=*


#
#
## Correct exclusion paths for Spring Boot 4.x
#spring.autoconfigure.exclude=\
#  org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
#  org.springframework.boot.jdbc.autoconfigure.DataSourceTransactionManagerAutoConfiguration,\
#  org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
#
#spring.web.cors.allowed-origin-patterns=http://localhost:5173
#spring.web.cors.allowed-methods=*
#spring.web.cors.allowed-headers=*





#spring.data.mongodb.uri=${mongodb+srv://adminuser:admin123@cluster0.frhup4t.mongodb.net/?appName=Cluster0}
# Correct exclusion paths for Spring Boot 4.x

spring.data.mongodb.uri=${MONGO_URI}

spring.autoconfigure.exclude=\
  org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
  org.springframework.boot.jdbc.autoconfigure.DataSourceTransactionManagerAutoConfiguration,\
  org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration

spring.web.cors.allowed-origin-patterns=http://localhost:5173
spring.web.cors.allowed-methods=*
spring.web.cors.allowed-headers=*